import type { Metadata } from "next";
import localFont from "next/font/local";
import { Montserrat } from "next/font/google"; // Import Google Font
import "./globals.css";
import NavBar from "./components/NavBar";
import { client } from "@/sanity/lib/client";
import { AppWrapper } from "@/context";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


      

// Add Montserrat font
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // Optional custom CSS variable
  weight: ["400", "500", "600", "700"], // Specify the weights you want
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {const data = await client.fetch(
  `*[_type == "product"]{
    price,
    title,
    "imageUrl": productImage.asset->url,
    tags,
    isNew,
    _id,
    discountPercentage,
    'slug': slug.current,
    description,
    tags
  }`
);
if(!data || data.length === 0){
  return (<div className="flex h-screen w-auto justify-center items-center">Product not found</div>)
};

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
      >
        <NavBar product={data}/>
        <AppWrapper>{children} <Toaster/></AppWrapper>
      </body>
    </html>
  );
}
